apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp:
  labels:
    app: lookyloo
  name: gke-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lookyloo
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        app: lookyloo
    spec:
      containers:
      # image: gcr.io/PROJECT_ID/IMAGE:TAG
      #  name: padsop
      - image: lookyloo-service
        name: lookyloo-container
      #- image: lookyloo-img
      #  name: lookyloo-container
