apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp:
  labels:
    app: lookyloo
  name: lookyloo-gke-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lookyloo
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        app: lookyloo
    spec:
      containers:
      # image: gcr.io/PROJECT_ID/IMAGE:TAG
      #  name: padsop
      #gcr.io/mythic-inn-323010/lookyloo-img
      #- image: gcr.io/$PROJECT_ID/$IMAGE:$TAG
      - image: gcr.io/PROJECT_ID/IMAGE:TAG
        name: lookyloo-container
      #- image: lookyloo-img
      #  name: lookyloo-container
