apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp:
  labels:
    app: lookyloo
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lookyloo
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        app: lookyloo
    spec:
      containers:
      - image: lookyloo-img
        name: gcr.io/PROJECT_ID/IMAGE:TAG
