apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: lookyloo
  name: lookyloo
  namespace: kustomize-demo
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: lookyloo
