apiVersion: v1
kind: Service
metadata:
  name: lookyloo-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8050
 # - name: test
 #   port: 4444
 #   protocol: TCP
  selector:
    app: lookyloo

---


apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: lookyloo
