apiVersion: v1
kind: Service
metadata:
  name: lookyloo-service
spec:
  type: LoadBalancer
  ports:
    - name: webapp
      port: 5100
    - name: port1
      port: 8050
    - name: port2
      port: 5023
 #   protocol: TCP
  selector:
    app: lookyloo-img

---


apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: lookyloo-img
